### PR TITLE
WET-BOEW-PHP demo site fix 2015-12-07

### PR DESCRIPTION
**Pull request by michael-milette**
WET-BOEW-PHP Fix for demo site. Changes also include:
- Now uses common content pages regardless of active theme.
- Now uses a common configuration file.
- Uses an optional cookie to keep track of active theme instead of maintaining content for each theme.
- Added theme switching using ?theme=themename in URL.
- License page now works regardless of theme used.
- Now includes support for the following themes:
  * wet-boew
  * base
  * gcwu-fegc
- Includes some Developer/Implementation documentation with
  instructions on how to make the demo site work.
- Now includes working sample config file which can be placed
  in one of two locations outside of repository.

Signed-off-by: Michael Milette <michael.milette@instruxmedia.com>

### CODE REVIEW

**Comment by upsonp** [comment]
Thanks @michael-milette, I'll have to look at dealing with the conflicts to merge this update in.

**Comment by michael-milette** [comment]
Hi @upsonp ,

You actually had most of it done. I just fixed it up a bit so that it would work.

I didn't notice any conflicts. If you can help me identify them, I don't mind fixing them.

Also note that this isn't done. Although it seems to be working fine, I did list a couple of known issues at the bottom of the DEVNOTES.txt file that you might want to look into. One of them was something called "Secondary Utility Menu Page". There is some code missing and I wasn't sure what you were trying to achieve here as there was no equivalent in the HTML dist version.

A couple of other changes to consider which I only though of after submitting the pull request:
1. The demos-php/config/config-default.php file is not required and should be deleted in order to avoid confusion.
2. To take flexibility a little further, you can replace the content of the demos-php/config.php/config.php with the code below to have have a common code based base supporting multiple domains:

    <?php
    // Programmatically set the main config file so that the site will work regardless of where it is.
    // Saves time when deploying a site to different servers for development.

    if (file_exists(__DIR__ . '/../../../wetconfig.php')) {
        // One level up from wet-boew-php.
        require_once __DIR__ . '/../../../wetconfig.php';
    } else if (file_exists($_SERVER['DOCUMENT_ROOT'] . '/wetconfig.php')) {
        // In the webroot of the server.
        require_once $_SERVER['DOCUMENT_ROOT'] . '/wetconfig.php';
    } else if (file_exists(__DIR__ . '/../../../wetconfig-'.$_SERVER['SERVER_NAME'].'.php')) {
        // Support for shared sites on different domains - One level up from wet-boew-php.
        require_once __DIR__ . '/../../../wetconfig-'.$_SERVER['SERVER_NAME'].'.php';
    } else if (file_exists($_SERVER['DOCUMENT_ROOT'] . '/wetconfig-'.$_SERVER['SERVER_NAME'].'.php')) {
        // Support for shared sites on different domains - In the webroot of the server.
        require_once $_SERVER['DOCUMENT_ROOT'] . '/-'.$_SERVER['SERVER_NAME'].'wetconfig.php';
    } else {
        die('The wetconfig.php file is missing. See WET-BOEW-PHP documentation for help.');
    }

This adds the ability to support multiple sites by having a copy of the wetconfig.php file for each domain. Just make a copy of the wetconfig.php naming it something like wetconfig-domainname.php, where domain name matches the domainname of each website. Example: wetconfig-www.example.com.php

Feel free to ask if you have any questions or concerns.

Best regards,

Michael

**Comment by upsonp** [comment]
I haven't had time to find the conflicts yet, but I get this image at the bottom of the pull request.

conflict

 I'll have to figure out what's causing the conflict before I can merge the request.

**Comment by michael-milette** [comment]
I think I figured it out. I noticed that the pull request went against the master branch instead of v4.0 branch. I'll submitting it again.

**Comment by michael-milette** [comment]
See https://github.com/wet-boew/wet-boew-php/pull/170 instead.

**Pull request closed without merging**
